analyzer:
  exclude:
    - lib/src/babylon/archive/**
    - tool/**
    - typescript/**
  errors:
    unused_element: info
    unused_import: info
    unused_local_variable: error
    dead_code: error
    override_on_non_overriding_method: error
